name: WolfDungeonsXL
version: ${project.version}
main: us.mytheria.wolfdungeonsxl.WolfDungeonsXL
api-version: 1.17
load: STARTUP
depend:
  - DungeonsXL
  - BlobLib
commands:
  dungeonlobby:
    description: attempts to add a lobby
  dungeonparty:
    description: attempts to manage parties